url: "https://rogancodes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Rogan Blog" # the name of your site, e.g. ACME Corp.
